// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8XgKDryHVTcniSDN048UT3vtvUAQec_M',
    appId: '1:207657627682:web:060f29cfb8f4e49333da7b',
    messagingSenderId: '207657627682',
    projectId: 'mobile-3a4fd',
    authDomain: 'mobile-3a4fd.firebaseapp.com',
    storageBucket: 'mobile-3a4fd.appspot.com',
    measurementId: 'G-SJEMNKR22L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd82VK6UEp8U70_qgCdZQDuCqbQRmbwYo',
    appId: '1:207657627682:android:566413af7ddfd7fb33da7b',
    messagingSenderId: '207657627682',
    projectId: 'mobile-3a4fd',
    storageBucket: 'mobile-3a4fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUW-xcN93M-VjvJU2NRNVTS6NSBhnEeCQ',
    appId: '1:207657627682:ios:a69b7ba77a1cfb5433da7b',
    messagingSenderId: '207657627682',
    projectId: 'mobile-3a4fd',
    storageBucket: 'mobile-3a4fd.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUW-xcN93M-VjvJU2NRNVTS6NSBhnEeCQ',
    appId: '1:207657627682:ios:a69b7ba77a1cfb5433da7b',
    messagingSenderId: '207657627682',
    projectId: 'mobile-3a4fd',
    storageBucket: 'mobile-3a4fd.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8XgKDryHVTcniSDN048UT3vtvUAQec_M',
    appId: '1:207657627682:web:18f18b23adbeec8033da7b',
    messagingSenderId: '207657627682',
    projectId: 'mobile-3a4fd',
    authDomain: 'mobile-3a4fd.firebaseapp.com',
    storageBucket: 'mobile-3a4fd.appspot.com',
    measurementId: 'G-XMJW9W173M',
  );
}
